spring:
  application:
    name: recommendationService
  ai:
    ollama:
      base-url: http://localhost:11434      # endpoint local de Ollama
      init:
        pull-model-strategy: always         # auto-descarga del modelo si falta
      embedding:
        model: mxbai-embed-large
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info